name: CI-DevSecOps

on:
  push:
    branches:
      - main

jobs:
  devsecops-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Unit Tests
        run: |
          npm install
          npm test

      - name: Lint Kubernetes Manifests
        uses: stackrox/kube-linter-action@v1
        with:
          manifest-dir: ./Kubernetes

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: your-dockerhub-username/your-image-name:latest

      - name: Secrets scan with Gitleaks
        uses: zricethezav/gitleaks-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t your-dockerhub-username/your-image-name:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push your-dockerhub-username/your-image-name:latest
